VERSION 0.8
FROM python:3
WORKDIR /code

sources:
    ARG version
    ENV PIP_ROOT_USER_ACTION=ignore

    COPY fasterui/ fasterui
    COPY pyproject.toml mypy.ini .
    RUN echo "__version__ = \"$version\"" > fasterui/__version__.py

wheel:
    ARG version
    FROM +sources --version $version

    RUN pip install build
    RUN python -m build
    SAVE ARTIFACT dist/fasterui-$version-py3-none-any.whl AS LOCAL dist/

build:
    ARG version
    ARG EARTHLY_GIT_SHORT_HASH

    FROM +wheel --version $version
    COPY +wheel/*.whl .
    RUN python -m pip install *.whl

    SAVE IMAGE --push ampiato/fasterui-dev:$EARTHLY_GIT_SHORT_HASH

openapi:
    FROM +build

    RUN python -m fasterui generate
    SAVE ARTIFACT openapi.json

code-quality:
    ARG version
    FROM +sources --version $version

    RUN pip install -e .
    RUN pip install mypy ruff
    RUN mypy .
    RUN ruff check .
    RUN ruff format --check .


ci:
    ARG version

    BUILD +build

    BUILD +code-quality --version $version
