VERSION 0.8
FROM node:22.6.0-bookworm-slim
WORKDIR /code

deps:
    ARG version
    COPY package.json ./
    RUN npm install
    COPY --dir .storybook lib public eslint.config.js index.html package.json postcss.config.js README.md tailwind.config.js tsconfig.json tslint.json vite.config.ts .
    RUN npm version --allow-same-version $version

build:
    ARG version
    FROM +deps --version $version
    RUN npm run build

storybook:
    ARG version
    FROM +build --version $version
    RUN npm run build:storybook
    SAVE ARTIFACT storybook-static/ AS LOCAL storybook-static/

ci:
    ARG version

    BUILD +build --version $version


