VERSION 0.8
FROM node:latest
WORKDIR /code

deps:
    COPY package.json ./
    RUN npm install
    COPY . .

build:
    FROM +deps
    RUN npm run build

storybook:
    FROM +build
    RUN npm run build:storybook
    SAVE ARTIFACT storybook-static
