VERSION 0.8
FROM node:latest
WORKDIR /code

deps:
    RUN npm install netlify-cli -g
    COPY package.json .
    RUN npm install netlify-cli --save-dev
    RUN npm install @netlify/plugin-nextjs --save-dev
    RUN npm install
    COPY . .

build:
    FROM +deps
    RUN --secret NETLIFY_AUTH_TOKEN --secret NETLIFY_SITE_ID netlify build --context production

deploy:
    FROM +build
    RUN --push --secret NETLIFY_AUTH_TOKEN --secret NETLIFY_SITE_ID netlify deploy --prod