[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
command = "npm run build && cp -r public/storybook ./.next/storybook"
publish = ".next"

[[redirects]]
from = "/_next/static/*"
to = "/static/:splat"
status = 200
force = true
