apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
    spec:
      containers:
      - name: fasterui
        image: ampiato/fasterui:{{ .Values.image.tag }}
        ports:
        - containerPort: 8000
          name: backend
---


apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    name: backend
    port: 8000
    targetPort: 8000
  selector:
    app: {{ .Release.Name }}-server
---

