apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-docs
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-docs
    spec:
      containers:
      - name: fasterui
        image: ampiato/fasterui-docs:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000
          name: frontend
---


apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-docs
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    name: frontend
    port: 3000
    targetPort: 3000
  selector:
    app: {{ .Release.Name }}-docs
---

