apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-server
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
spec:
  ingressClassName: nginx
  tls: 
  - hosts:
    - fasterui.ampiato.com
    secretName: {{ .Release.Name }}-production-cert
  rules:
    - host: fasterui.ampiato.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-server
                port:
                  number: 8000

          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-docs
                port:
                  number: 3000
