apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    name: backend
    port: 8000
    targetPort: 8000
  selector:
    app: {{ .Release.Name }}-server