name: Deploy


on:
  workflow_dispatch:


jobs:
  staging:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: env
      run: env
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build metadata
      run: |
        if [[ "$GITHUB_REF_TYPE" == "branch" ]]; then
          RELEASE_VERSION="0.1.0"
          DOCKER_TAG="$GITHUB_SHA"
          SUFFIX="-staging"
        elif [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
          RELEASE_VERSION="${GITHUB_REF#refs/tags/}"
          DOCKER_TAG="$RELEASE_VERSION"
          SUFFIX=""
        fi

        echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
        echo "$DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
        echo "SUFFIX=$SUFFIX" >> $GITHUB_ENV

    - name: Deploy Staging
      run: |
        mkdir -p ~/.kube
        echo "$KUBERNETES_CONFIG" > ~/.kube/config

        ./deployment/deploy_staging.sh $RELEASE_VERSION $SUFFIX

      env:
        KUBERNETES_CONFIG: ${{ secrets.KUBERNETES_CONFIG }}

