name: Earthly CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]
  release:
    types: [published]
  

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - uses: actions/checkout@v4
      - name: env
        run: env
      - name: Run build
        run: earthly --artifact '+artifacts/*' ./dist/ --push +ci --version 0.1.0
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - uses: actions/checkout@v4
      - name: Run deploy
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          earthly \
            --secret NETLIFY_AUTH_TOKEN \
            --secret NETLIFY_SITE_ID \
            --secret NPM_PUBLSH_KEY \
            --secret TWINE_PASSWORD \
            --ci --push +deploy --version $RELEASE_VERSION
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NPM_PUBLSH_KEY: ${{ secrets.NPM_PUBLSH_KEY }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      - name: Extract artifacts
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          earthly --artifact '+artifacts/*' ./dist/ --push +artifacts --version $RELEASE_VERSION
          cd dist
          zip -r storybook.zip storybook-static
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/openapi.json
            dist/storybook.zip
            dist/*.whl

          