name: Earthly CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - uses: actions/checkout@v4
      - name: Run build
        run: earthly --ci --push +ci

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # if: github.ref == 'refs/heads/main'

    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - uses: actions/checkout@v4
      - name: Run deploy
        run: earthly --secret NETLIFY_AUTH_TOKEN --secret NETLIFY_SITE_ID --ci --push +deploy-docs
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
