name: Earthly CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]
  

jobs:
  earthly:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: env
        run: env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0

      - name: Build metadata
        run: |
          if [[ "$GITHUB_REF_TYPE" == "branch" ]]; then
            RELEASE_VERSION="0.1.0"
            DOCKER_TAG="$GITHUB_SHA"
            SUFFIX="-staging"
          elif [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
            RELEASE_VERSION="${GITHUB_REF#refs/tags/}"
            DOCKER_TAG="$RELEASE_VERSION"
            SUFFIX=""
          fi

          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "$DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
          echo "SUFFIX=$SUFFIX" >> $GITHUB_ENV

          cat $GITHUB_ENV
 
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          earthly \
            --artifact '+artifacts/*' ./dist/ \
            --push +ci --version $RELEASE_VERSION

          cd dist
          zip -r storybook.zip storybook-static

      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: dist

      - name: Build fasterui image
        run: |
          docker build . -f python/Dockerfile -t ampiato/fasterui$SUFFIX:$DOCKER_TAG
          docker push ampiato/fasterui$SUFFIX:$DOCKER_TAG

      - name: Build fasterui-docs image
        run: |
          cd docs
          docker build . -t ampiato/fasterui-docs$SUFFIX:$DOCKER_TAG 
          docker push ampiato/fasterui-docs$SUFFIX:$DOCKER_TAG