name: Earthly CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]
  release:
    types: [published]
  

jobs:
  earthly:
    runs-on: ubuntu-latest

    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - uses: actions/checkout@v4
      - name: env
        run: env
      - name: Run build
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            RELEASE_VERSION="${GITHUB_REF#refs/tags/}"
            earthly \
              --secret NETLIFY_AUTH_TOKEN \
              --secret NETLIFY_SITE_ID \
              --secret NPM_PUBLSH_KEY \
              --secret TWINE_PASSWORD \
              --artifact '+artifacts/*' ./dist/ \
              --ci --push +deploy --version $RELEASE_VERSION
          else
            earthly \
              --artifact '+artifacts/*' ./dist/ \
              --ci --push +ci --version 0.1.0
          fi

          cd dist
          zip -r storybook.zip storybook-static
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NPM_PUBLSH_KEY: ${{ secrets.NPM_PUBLSH_KEY }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: dist
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/openapi.json
            dist/storybook.zip
            dist/*.whl
