name: Earthly CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]
  

jobs:
  earthly:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: env
        run: env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0

      - name: Build metadata
        run: |
          if [[ "$GITHUB_REF_TYPE" == "branch" ]]; then
            RELEASE_VERSION="0.1.0"
            DOCKER_TAG="$GITHUB_SHA"
            SUFFIX="-staging"
          elif [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
            RELEASE_VERSION="${GITHUB_REF#refs/tags/}"
            DOCKER_TAG="$RELEASE_VERSION"
            SUFFIX=""
          fi

          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
          echo "SUFFIX=$SUFFIX" >> $GITHUB_ENV

          cat $GITHUB_ENV
 
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          earthly \
            --artifact '+artifacts/*' ./dist/ \
            --push +ci --version $RELEASE_VERSION

          cd dist
          zip -r storybook.zip storybook-static

      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: dist

      - name: Build fasterui image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: python/Dockerfile
          push: true
          tags: ampiato/fasterui${{ env.SUFFIX }}:${{ env.DOCKER_TAG }}

      - name: Build fasterui-docs image
        uses: docker/build-push-action@v6
        with:
          context: docs
          platforms: linux/amd64,linux/arm64
          file: docs/Dockerfile
          push: true
          tags: ampiato/fasterui-docs${{ env.SUFFIX }}:${{ env.DOCKER_TAG }}
