name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - uses: actions/checkout@v4
      - name: Run build
        run: earthly --ci --push +all