name: Deploy

on:
  push:
    tags:
      - '*'
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: env
        run: env

      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0

      - uses: actions/checkout@v4

      - name: Build metadata
        run: |
          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}

      - name: Run tests
        run: |
          RELEASE_VERSION="${GITHUB_REF#refs/tags/}"
            earthly \
              --artifact '+artifacts/*' ./dist/ \
              --push +ci --version $RELEASE_VERSION
          earthly \
              --secret NETLIFY_AUTH_TOKEN \
              --secret NETLIFY_SITE_ID \
              --secret NPM_PUBLSH_KEY \
              --secret TWINE_PASSWORD \
              --ci --push +deploy --version $RELEASE_VERSION

          cd dist
          zip -r storybook.zip storybook-static
         env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NPM_PUBLSH_KEY: ${{ secrets.NPM_PUBLSH_KEY }}
            TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: dist

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
        files: |
            dist/openapi.json
            dist/storybook.zip
            dist/*.whl